- name: Update Helm Chart Tag
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/moti-art/weather-gitops.git
          cd weather-gitops/charts/weather-app
          
          # פקודת ה-sed הזו מחפשת את ה-tag שנמצא תחת tracker:
          # אנחנו אומרים לו: חפש 2 שורות אחרי המילה tracker ותחליף את ה-tag
          sed -i '/tracker:/,/tag:/ s/tag: .*/tag: "${{ github.sha }}"/' values-dev.yaml

          if git diff --quiet; then
            echo "No changes"
          else
            git add values-dev.yaml
            git commit -m "chore: update tracker tag to ${{ github.sha }}"
            git push
          fi